
name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd poc-github-actions
          ls -la

  job-public-repo-macos:
    runs-on: macos-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd poc-github-actions
          ls -la

  job-public-repo-windows:
    runs-on: windows-latest
    steps:
      
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@main
        with:
          owner: 'GuillaumeFalourd'
          repository: 'poc-github-actions'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd poc-github-actions
          ls -la
        shell: bash
